name: Playwright UI Tests (via NGROK)

on:
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # -------------------
      # Checkout
      # -------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # -------------------
      # Setup Python
      # -------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # -------------------
      # Install dependencies
      # -------------------
      - name: Install Python dependencies
        working-directory: ui
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------
      # Install Playwright browsers
      # -------------------
      - name: Install Playwright browsers
        run: playwright install chromium

      # -------------------
      # Run Playwright tests
      # -------------------
      - name: Run Playwright tests
        working-directory: ui
        env:
          HEADLESS: true
          APP_URL: https://lichenlike-kellee-autocratically.ngrok-free.dev
        run: |
          pytest tests/ -v
