name: UI Tests Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # -------------------
      # Install UI deps
      # -------------------
      - name: Install UI dependencies
        working-directory: ui
        run: npm install --legacy-peer-deps


      # -------------------
      # Start UI server
      # -------------------
      - name: Start UI (Next.js)
        working-directory: ui
        run: |
          npm run dev &
          npx wait-on http://localhost:3000

      # -------------------
      # Install Playwright deps
      # -------------------
      - name: Install Playwright dependencies
        working-directory: ui
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      # -------------------
      # Run SMOKE tests
      # -------------------
      - name: Run SMOKE tests
        working-directory: ui
        env:
          BASE_URL: http://localhost:3000
        run: pytest -m smoke


  feature:
    name: Feature Tests
    runs-on: ubuntu-22.04
    needs: smoke

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install UI dependencies
        working-directory: ui
        run: npm install --legacy-peer-deps

      - name: Start UI
        working-directory: ui
        run: |
          npm run dev &
          npx wait-on http://localhost:3000

      - name: Install Playwright dependencies
        working-directory: ui
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run FEATURE tests
        working-directory: ui
        env:
          BASE_URL: http://localhost:3000
        run: pytest -m feature


  e2e:
    name: E2E Tests
    runs-on: ubuntu-22.04
    needs: feature

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install UI dependencies
        working-directory: ui
        run: npm install --legacy-peer-deps


      - name: Start UI
        working-directory: ui
        run: |
          npm run dev &
          npx wait-on http://localhost:3000

      - name: Install Playwright dependencies
        working-directory: ui
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run E2E tests
        working-directory: ui
        env:
          BASE_URL: http://localhost:3000
        run: pytest -m e2e
