name: UI Tests Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-22.04


    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ui
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run SMOKE tests
        working-directory: ui
        env:
          BASE_URL: https://lichenlike-kellee-autocratically.ngrok-free.dev
        run: pytest -m smoke

  feature:
    name: Feature Tests
    runs-on: ubuntu-22.04
    needs: smoke

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ui
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run FEATURE tests
        working-directory: ui
        run: pytest -m feature

  e2e:
    name: E2E Tests
    runs-on: ubuntu-22.04
    needs: feature

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ui
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run E2E tests
        working-directory: ui
        run: pytest -m e2e
